#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := mqtt_ssl_mutual_auth

# EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/common_components/protocol_examples_common

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/Lm-Study/ssl_mutual_auth/main/device
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/Lm-Study/ssl_mutual_auth/main/network
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/Lm-Study/ssl_mutual_auth/main/tuya

include $(IDF_PATH)/make/project.mk
